'use strict'

// Builds the self-contained Node.js commit-msg hook script that is written to
// disk (e.g. .githooks/commit-msg or .git/hooks/commit-msg). The generated
// script has no runtime dependency on this package: it inlines the strip
// function source and the pattern constants, and optionally reads
// .no-coauthorrc.json from the repo root and the user's home directory.
//
// The installer wraps this script between START/END markers so it can be
// appended to an existing hook and cleanly removed later.

var strip = require('./strip')
var patterns = require('./patterns')

function buildHook() {
  var patternsJson = JSON.stringify({
    AI_NAMES: patterns.AI_NAMES,
    BOT_EMAIL_PATTERNS: patterns.BOT_EMAIL_PATTERNS,
    AI_TOOL_DOMAINS: patterns.AI_TOOL_DOMAINS
  })

  return (
    '#!/usr/bin/env node\n' +
    '// no-coauthor-managed (do not remove; used by uninstall)\n' +
    "'use strict'\n" +
    '// no-coauthor — strips AI co-author trailers from commit messages.\n' +
    '// Generated by no-coauthor. Self-contained: no runtime require of no-coauthor.\n' +
    'var fs = require("fs")\n' +
    'var os = require("os")\n' +
    'var path = require("path")\n' +
    'var file = process.argv[2]\n' +
    'if (!file) process.exit(0)\n' +
    '// NO_COAUTHOR_DISABLE=1 disables just this hook for one commit/session,\n' +
    '// unlike --no-verify which skips every hook (including any preserved\n' +
    '// foreign one this may be wrapping).\n' +
    'if (process.env.NO_COAUTHOR_DISABLE) process.exit(0)\n' +
    '\n' +
    'var patterns = ' + patternsJson + '\n' +
    'var escapeRe = ' + strip.escapeRe.toString() + '\n' +
    'var stripMessage = ' + strip.stripMessage.toString() + '\n' +
    '\n' +
    'function readConfig() {\n' +
    '  var extra = { extraNames: [], extraEmails: [], extraDomains: [] }\n' +
    '  // Homedir config is the user\'s own machine, always trusted. Repo-local\n' +
    '  // config (cwd) is NOT trusted by default: a cloned repo could ship a\n' +
    '  // .no-coauthorrc.json that strips real human co-author attribution.\n' +
    '  // Opt into repo config with NO_COAUTHOR_TRUST_REPO=1.\n' +
    '  var trustRepo = process.env.NO_COAUTHOR_TRUST_REPO === "1" || process.env.NO_COAUTHOR_TRUST_REPO === "true"\n' +
    '  var candidates = [path.join(os.homedir(), ".no-coauthorrc.json")]\n' +
    '  if (trustRepo) candidates.push(path.join(process.cwd(), ".no-coauthorrc.json"))\n' +
    '  candidates.forEach(function (p) {\n' +
    '    try {\n' +
    '      var j = JSON.parse(fs.readFileSync(p, "utf8"))\n' +
    '      if (Array.isArray(j.names)) extra.extraNames = extra.extraNames.concat(j.names)\n' +
    '      if (Array.isArray(j.emails)) extra.extraEmails = extra.extraEmails.concat(j.emails)\n' +
    '      if (Array.isArray(j.domains)) extra.extraDomains = extra.extraDomains.concat(j.domains)\n' +
    '    } catch (e) {}\n' +
    '  })\n' +
    '  return extra\n' +
    '}\n' +
    '\n' +
    'try {\n' +
    '  var cfg = readConfig()\n' +
    '  var msg = fs.readFileSync(file, "utf8")\n' +
    '  var cleaned = stripMessage(msg, cfg)\n' +
    '  if (cleaned !== msg) fs.writeFileSync(file, cleaned)\n' +
    '} catch (e) {\n' +
    '  // Never block a commit because of our own failure. No color lib here:\n' +
    '  // this script is self-contained by design (no require of no-coauthor\n' +
    '  // or any npm dep), so the escape code is written raw. Mirrors\n' +
    '  // picocolors\' own rule (see lib/ui.js) so this rare error line matches\n' +
    '  // the rest of the tool: NO_COLOR wins, else FORCE_COLOR/CI force it on,\n' +
    '  // else fall back to stderr being an interactive, non-"dumb" terminal.\n' +
    '  var useColor =\n' +
    '    !process.env.NO_COLOR &&\n' +
    '    (process.env.FORCE_COLOR || process.env.CI || (process.stderr.isTTY && process.env.TERM !== "dumb"))\n' +
    '  var tag = useColor ? "\\u001b[1m\\u001b[31mno-coauthor\\u001b[0m" : "no-coauthor"\n' +
    '  process.stderr.write(tag + ": " + (e && e.message ? e.message : String(e)) + "\\n")\n' +
    '}\n'
  )
}

module.exports = buildHook()
